
all: p1 p2 p3 p4 c5_1 c5_2 c5_4 c5_6 c5_8

clean:
	rm -f p1 p2 p3 p4

p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

c5_1: chapter5_1.c
	gcc -o c5_1 chapter5_1.c -Wall

c5_2: chapter5_2.c
	gcc -o c5_2 chapter5_2.c -Wall

c5_4: chapter5_4.c
	gcc -o c5_4 chapter5_4.c -Wall

c5_6: chapter5_6.c
	gcc -o c5_6 chapter5_6.c -Wall

c5_8: chapter5_8.c
	gcc -o c5_8 chapter5_8.c -Wall